added models and auth
paw9810/ChatApp pull request #1
Opened 2021-08-12 19:59 UTC by paw9810

2021-08-12 20:46 UTC, WadasGrzegorz requested changes

2021-08-12 20:46 UTC, WadasGrzegorz commented on .gitignore
> +ormconfig.json
please add new line at end of each file

2021-08-12 20:46 UTC, WadasGrzegorz commented on package.json
> +        "@nestjs/config": "^1.0.1",
remove `^` from every package - we use strict package version

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/lib/entities/chat.entity.ts
> +    id: number
every id should contain table name for eg. `chatId`

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/lib/entities/chat.entity.ts
> +    name: string
aa `chatName`

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/lib/entities/member.entity.ts
> +    id: number
aa

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/lib/entities/user.entity.ts
> +    @Column()
FYI - You can also use `@Column({ select: false })`

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/lib/guards/jwt-auth.guard.ts
> +export class JwtAuthGuard extends AuthGuard('jwt') {}
use enum for example `AuthType`

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/app/app.module.ts
> +import { User, Chat, Member, Message } from 'lib/entities/'
remove `/`

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/app/app.module.ts
> +import { getConnectionOptions } from 'typeorm'
import order - every package that you imported from node modules should be on top, next are You global imports for eg 'lib/entities' the last one is local imports

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/app/app.module.ts
> +        TypeOrmModule.forFeature([User, Chat, Member, Message]),
forFeature import should be only in models where you using this entities

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +import { LocalAuthGuard, JwtAuthGuard } from '../../lib/guards/'
change to `'lib/guards'` and import order :)

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +import { CreateUserDto } from '../users/dto/create-user.dto'
?

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +    @UseGuards(JwtAuthGuard)
You should use this guard globally and exclude only some path

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +    async login(@Req() req: any) {
`any` type is forbidden - in this place You can use Request imported form express

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +    getProfile(@Req() req: any) {
aa

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +import { PassportModule } from '@nestjs/passport'
import oder

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +import { JwtStrategy } from './jwt.strategy'
You should create folder like `strategies` and put there every strategy

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +                signOptions: { expiresIn: '60s' },
in real example 60s is a little too short :)

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +                secret: configService.get<string>('JWT_SECRET'),
`JWT_SECRET` should be in enum

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +        ConfigModule,
I think that is no need to import config module here - You declared it globally

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +console.log(process.env.JWT_SECRET)
console.log is forbidden in PR

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +import * as bcrypt from 'bcrypt'
import order

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/users/users.service.ts
> +    async findOne(username: string) {
camelcase: `userName`

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +import { UsersService } from '../users/users.service'
bad import - should be like '../users' or 'modules/user' but I don't think that import dot from user module is correct

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +        private usersService: UsersService,
`private readonly`

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +        const user = await this.usersService.findOne(username)
enter before if

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +    async validateUser(username: string, pass: string): Promise<any> {
don't use any

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +    async login(user: any) {
aa

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +    async login(user: any) {
if You not using await then You not need async

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/local.strategy.ts
> +        if (!user) {
aa

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/auth/local.strategy.ts
> +    async validate(username: string, password: string): Promise<any> {
aa

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/users/dto/create-user.dto.ts
> +    username: string
camelcase

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/users/dto/create-user.dto.ts
> +    email: string
add readonly

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/users/users.module.ts
> +import { TypeOrmModule } from '@nestjs/typeorm'
aa

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/users/users.service.ts
> +import { CreateUserDto } from './dto/create-user.dto'
aa

2021-08-12 20:46 UTC, WadasGrzegorz commented on src/modules/users/users.service.ts
> +            const user = await this.usersRepository.create({
`
return this.usersRepository.save({
                 username,
                 email,
                 password: hashedPassword,
             })
`

2021-08-13 21:47 UTC, paw9810 commented on src/modules/users/dto/create-user.dto.ts
> +    email: string
I don't understand where

2021-08-13 21:49 UTC, paw9810 commented on src/modules/users/users.service.ts
> +            const user = await this.usersRepository.create({
I left it as it is because after change excluding password didn't work

2021-08-13 21:50 UTC, paw9810 commented on src/modules/auth/auth.controller.ts
> +import { CreateUserDto } from '../users/dto/create-user.dto'
Should I create separate dto in auth module?

2021-08-15 14:14 UTC, WadasGrzegorz commented on src/modules/users/dto/create-user.dto.ts
> +    email: string
```readonly email: string```

2021-08-15 14:41 UTC, WadasGrzegorz requested changes

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/entities/user.entity.ts
> +import { Message } from '.'
.

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/guards/jwt-auth.guard.ts
> +import { IS_PUBLIC_KEY } from 'lib/decorators/public-route'
.

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/guards/jwt-auth.guard.ts
> +import { IS_PUBLIC_KEY } from 'lib/decorators/public-route'
and add enter after imports

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/guards/jwt-auth.guard.ts
> +        )
enter before if

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/guards/jwt-auth.guard.ts
> +        const isPublic = this.reflector.getAllAndOverride<boolean>(
are You sure that You want to use `this.reflector.getAndOverride` instead `this.reflector.get` ?

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/strategies/local.strategy.ts
> +import { AuthService } from '../../modules/auth/auth.service'
if You want to use AuthService externally you should export it from index

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/strategies/local.strategy.ts
> +        if (!user) {
enter before if

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +import { CreateUserDto } from '../users/dto/create-user.dto'
yes - second option is export this dto from module

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +import { ILoginUserRequest } from './interfaces/login-user.interface.ts'
folder interfaces should have index.

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/lib/entities/user.entity.ts
> +import { Exclude } from 'class-transformer'
import order

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/users/users.service.ts
> +            const user = await this.usersRepository.create({
ok, that why I always use option `select: false` in entity column option

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/users/users.service.ts
> +    ) {}
enter

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/users/users.service.ts
> +import { CreateUserDto } from './dto/create-user.dto'
dto should also have index.ts

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/users/users.module.ts
> +import { UsersController } from './users.controller'
enter after import

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/users/dto/create-user.dto.ts
> +import { MaxLength, IsNotEmpty, IsString, IsEmail } from 'class-validator'
enter after import

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +        const payload = { username: user.userName, sub: user.userId }
`userName`

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +    async validateUser(username: string, pass: string): Promise<User | null> {
camelcase

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +            const result = user
`return user` ? :)

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +import { CreateUserDto } from '../users/dto/create-user.dto'
dto should have index

2021-08-15 14:41 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +import { AuthController } from './auth.controller'
enter

2021-08-17 07:05 UTC, WadasGrzegorz requested changes

2021-08-17 07:05 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +    ],
add `exports: [AuthService]`

2021-08-17 07:05 UTC, WadasGrzegorz commented on src/lib/strategies/local.strategy.ts
> +    onModuleInit() {
remove it

2021-08-17 07:05 UTC, WadasGrzegorz commented on src/lib/strategies/local.strategy.ts
> +    implements OnModuleInit {
remove implements

2021-08-17 07:05 UTC, WadasGrzegorz commented on src/lib/strategies/local.strategy.ts
> +    constructor(private moduleRef: ModuleRef) {
now if you export auth service from module you can easily use in this place
```
private readonly authService: AuthService
```

2021-08-17 07:05 UTC, WadasGrzegorz commented on src/modules/users/dto/create-user.dto.ts
> +    userName: string
add `readonly` in every dto item

2021-08-17 07:33 UTC, paw9810 commented
When I import AuthService like this it works:
`import { AuthService } from 'modules/auth/auth.service'`
but when I do this, the app crashes:
`import { AuthService } from 'modules/auth'`
![image](https://user-images.githubusercontent.com/17554594/129683518-d5b4aab0-ec77-4b83-beb2-85c479848741.png)

2021-08-17 14:47 UTC, WadasGrzegorz requested changes

2021-08-17 14:47 UTC, WadasGrzegorz commented on src/modules/auth/auth.module.ts
> +import { JwtStrategy, LocalStrategy } from 'modules/auth/strategies'
```import { JwtStrategy, LocalStrategy } from '../strategies'```

2021-08-17 14:47 UTC, WadasGrzegorz commented on src/modules/auth/strategies/interfaces/payload.interface.ts
> +export interface IPayload {
it can be just `type` if You not extend it

2021-08-17 15:00 UTC, WadasGrzegorz approved these changes

2021-08-17 15:00 UTC, merged