added logout and redis module
paw9810/ChatApp pull request #2
Opened 2021-08-18 14:21 UTC by paw9810

2021-08-18 14:42 UTC, WadasGrzegorz requested changes

2021-08-18 14:42 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +        await this.redisService.setToken(token, user.userId)
use key like `access-token-userUUID`

2021-08-18 14:42 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +        return 'Successfully logged out'
no magic string - if you need that You can create const with translations

2021-08-18 14:42 UTC, WadasGrzegorz commented on src/modules/auth/strategies/jwt.strategy.ts
> +        private configService: ConfigService,
in this place also readonly

2021-08-18 14:42 UTC, WadasGrzegorz commented on src/modules/auth/strategies/jwt.strategy.ts
> +        const token = await this.redisService.getToken(payload.sub)
create in authService method like `validateAccessToken(userUUID: string, token: string)`

2021-08-18 14:42 UTC, WadasGrzegorz commented on src/modules/redis/redis.service.ts
> +    async getToken(userId: number) {
just return this.cacheManager

2021-08-19 11:58 UTC, WadasGrzegorz requested changes

2021-08-19 11:58 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +        const uuid = uuidv4()
use userUUID instead create new one

2021-08-19 11:58 UTC, WadasGrzegorz commented on src/modules/redis/redis.service.ts
> +export class RedisService {
You should think about create this service more common

2021-08-21 10:36 UTC, paw9810 commented on src/modules/auth/auth.service.ts
> +        const uuid = uuidv4()
You mean to create userUUID in user entity?

2021-08-21 18:34 UTC, paw9810 commented on src/modules/redis/redis.service.ts
> +export class RedisService {
So should I just create 3 basic methods and use them in other services?

2021-08-22 09:22 UTC, WadasGrzegorz commented on src/modules/redis/redis.service.ts
> +export class RedisService {
Exactly, I recommend some methods like set, get, delete. If You do this you can use this module elsewhere

2021-08-22 09:26 UTC, WadasGrzegorz commented on src/modules/auth/auth.service.ts
> +        const uuid = uuidv4()
Yes, please use for this ’@generated’ decorator from typeorm

2021-08-22 10:10 UTC, paw9810 commented
I have a problem with this approach with userUUID, because when I'm not generating a new one with every login, the validation will pass even with old tokens

2021-08-23 13:16 UTC, WadasGrzegorz requested changes

2021-08-23 13:16 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +    @Post('logout')
use no-content

2021-08-23 13:16 UTC, WadasGrzegorz commented on src/modules/redis/redis.service.ts
> +        await this.cacheManager.set(key, value, { ttl })
await is not necessary just return

2021-08-23 13:16 UTC, WadasGrzegorz commented on src/modules/redis/redis.service.ts
> +        await this.cacheManager.del(key)
aa

2021-08-23 14:17 UTC, WadasGrzegorz requested changes

2021-08-23 14:17 UTC, WadasGrzegorz commented on src/modules/auth/auth.controller.ts
> +    @HttpCode(204)
It's enum available in nest ```import { HttpStatus } from '@nestjs/common'``` and then ``` @HttpCode(HttpStatus.NO_CONTENT)```

2021-08-23 14:17 UTC, WadasGrzegorz commented on src/modules/auth/strategies/jwt.strategy.ts
> +        if (user) {
enter before if

2021-08-23 14:22 UTC, WadasGrzegorz approved these changes

2021-08-23 14:22 UTC, merged